//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artigo()
        {
            this.Ficheiroes = new HashSet<Ficheiro>();
            this.Revisaos = new HashSet<Revisao>();
            this.Submissaos = new HashSet<Submissao>();
        }
    
        public int identificador { get; set; }
        public string resumo { get; set; }
        public Nullable<System.DateTime> dataSubmissao { get; set; }
        public string nomeConferencia { get; set; }
        public int anoConferencia { get; set; }
        public string estado { get; set; }
    
        public virtual Conferencia Conferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ficheiro> Ficheiroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revisao> Revisaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submissao> Submissaos { get; set; }
    }
}
