//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conferencia()
        {
            this.Artigoes = new HashSet<Artigo>();
            this.Inscricaos = new HashSet<Inscricao>();
        }
    
        public string nome { get; set; }
        public int anoRealizacao { get; set; }
        public string acronimo { get; set; }
        public System.DateTime dataLimiteRevisao { get; set; }
        public System.DateTime dataLimiteSubmissao { get; set; }
        public string emailPresidente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigoes { get; set; }
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscricao> Inscricaos { get; set; }
    }
}
