//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagerEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConferênciaAcadémicaEntities : DbContext
    {
        public ConferênciaAcadémicaEntities()
            : base("name=ConferênciaAcadémicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigo> Artigoes { get; set; }
        public virtual DbSet<Conferencia> Conferencias { get; set; }
        public virtual DbSet<Ficheiro> Ficheiroes { get; set; }
        public virtual DbSet<Inscricao> Inscricaos { get; set; }
        public virtual DbSet<Instituicao> Instituicaos { get; set; }
        public virtual DbSet<Revisao> Revisaos { get; set; }
        public virtual DbSet<Submissao> Submissaos { get; set; }
        public virtual DbSet<Utilizador> Utilizadors { get; set; }
    
        public virtual int AtribuirPapelAutor(string idArtigo, string email, Nullable<bool> responsavel, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var idArtigoParameter = idArtigo != null ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var responsavelParameter = responsavel.HasValue ?
                new ObjectParameter("responsavel", responsavel) :
                new ObjectParameter("responsavel", typeof(bool));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtribuirPapelAutor", idArtigoParameter, emailParameter, responsavelParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtribuirPapelPresidente(string email, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtribuirPapelPresidente", emailParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtribuirPapelRevisor(Nullable<int> idArtigo, string email, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var idArtigoParameter = idArtigo.HasValue ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtribuirPapelRevisor", idArtigoParameter, emailParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtribuirRevisor(string emailRevisor, Nullable<int> idArtigo, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var emailRevisorParameter = emailRevisor != null ?
                new ObjectParameter("emailRevisor", emailRevisor) :
                new ObjectParameter("emailRevisor", typeof(string));
    
            var idArtigoParameter = idArtigo.HasValue ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(int));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtribuirRevisor", emailRevisorParameter, idArtigoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtualizarConferenciaDataLimiteRevisao(Nullable<System.DateTime> dataRevisao, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var dataRevisaoParameter = dataRevisao.HasValue ?
                new ObjectParameter("dataRevisao", dataRevisao) :
                new ObjectParameter("dataRevisao", typeof(System.DateTime));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarConferenciaDataLimiteRevisao", dataRevisaoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtualizarConferenciaDataLimiteSubmissao(Nullable<System.DateTime> dataSubmissao, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var dataSubmissaoParameter = dataSubmissao.HasValue ?
                new ObjectParameter("dataSubmissao", dataSubmissao) :
                new ObjectParameter("dataSubmissao", typeof(System.DateTime));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarConferenciaDataLimiteSubmissao", dataSubmissaoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtualizarConferenciaPresidente(string emailPres, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var emailPresParameter = emailPres != null ?
                new ObjectParameter("emailPres", emailPres) :
                new ObjectParameter("emailPres", typeof(string));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarConferenciaPresidente", emailPresParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtualizarEstado(string estadoNovo, Nullable<int> idArtigo, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var estadoNovoParameter = estadoNovo != null ?
                new ObjectParameter("estadoNovo", estadoNovo) :
                new ObjectParameter("estadoNovo", typeof(string));
    
            var idArtigoParameter = idArtigo.HasValue ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(int));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarEstado", estadoNovoParameter, idArtigoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int AtualizarUtilizador(string email, string nomeInstituicao)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nomeInstituicaoParameter = nomeInstituicao != null ?
                new ObjectParameter("nomeInstituicao", nomeInstituicao) :
                new ObjectParameter("nomeInstituicao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarUtilizador", emailParameter, nomeInstituicaoParameter);
        }
    
        public virtual int InserirArtigo(Nullable<int> id, string resumo, Nullable<System.DateTime> dataSubmissao, string nomeConferencia, Nullable<int> anoConferencia, string autor, Nullable<bool> responsavel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resumoParameter = resumo != null ?
                new ObjectParameter("resumo", resumo) :
                new ObjectParameter("resumo", typeof(string));
    
            var dataSubmissaoParameter = dataSubmissao.HasValue ?
                new ObjectParameter("dataSubmissao", dataSubmissao) :
                new ObjectParameter("dataSubmissao", typeof(System.DateTime));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var responsavelParameter = responsavel.HasValue ?
                new ObjectParameter("responsavel", responsavel) :
                new ObjectParameter("responsavel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserirArtigo", idParameter, resumoParameter, dataSubmissaoParameter, nomeConferenciaParameter, anoConferenciaParameter, autorParameter, responsavelParameter);
        }
    
        public virtual int InserirUtilizador(string email, string nome, string nomeInstituicao, Nullable<System.DateTime> dataRegisto, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var nomeInstituicaoParameter = nomeInstituicao != null ?
                new ObjectParameter("nomeInstituicao", nomeInstituicao) :
                new ObjectParameter("nomeInstituicao", typeof(string));
    
            var dataRegistoParameter = dataRegisto.HasValue ?
                new ObjectParameter("dataRegisto", dataRegisto) :
                new ObjectParameter("dataRegisto", typeof(System.DateTime));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserirUtilizador", emailParameter, nomeParameter, nomeInstituicaoParameter, dataRegistoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int ListarRevisores(Nullable<int> idArtigo, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var idArtigoParameter = idArtigo.HasValue ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(int));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListarRevisores", idArtigoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int RegistarRevisao(Nullable<System.DateTime> dataRevisao, Nullable<int> notaMinima, Nullable<int> nota, string texto, Nullable<int> idArtigo, string emailRevisor, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var dataRevisaoParameter = dataRevisao.HasValue ?
                new ObjectParameter("dataRevisao", dataRevisao) :
                new ObjectParameter("dataRevisao", typeof(System.DateTime));
    
            var notaMinimaParameter = notaMinima.HasValue ?
                new ObjectParameter("notaMinima", notaMinima) :
                new ObjectParameter("notaMinima", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(int));
    
            var textoParameter = texto != null ?
                new ObjectParameter("texto", texto) :
                new ObjectParameter("texto", typeof(string));
    
            var idArtigoParameter = idArtigo.HasValue ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(int));
    
            var emailRevisorParameter = emailRevisor != null ?
                new ObjectParameter("emailRevisor", emailRevisor) :
                new ObjectParameter("emailRevisor", typeof(string));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistarRevisao", dataRevisaoParameter, notaMinimaParameter, notaParameter, textoParameter, idArtigoParameter, emailRevisorParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int RemoverArtigo(Nullable<int> idArtigo, string nomeConferencia, Nullable<int> anoConferencia)
        {
            var idArtigoParameter = idArtigo.HasValue ?
                new ObjectParameter("idArtigo", idArtigo) :
                new ObjectParameter("idArtigo", typeof(int));
    
            var nomeConferenciaParameter = nomeConferencia != null ?
                new ObjectParameter("nomeConferencia", nomeConferencia) :
                new ObjectParameter("nomeConferencia", typeof(string));
    
            var anoConferenciaParameter = anoConferencia.HasValue ?
                new ObjectParameter("anoConferencia", anoConferencia) :
                new ObjectParameter("anoConferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoverArtigo", idArtigoParameter, nomeConferenciaParameter, anoConferenciaParameter);
        }
    
        public virtual int RemoverUtilizador(string email, string nomeInstituicao)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nomeInstituicaoParameter = nomeInstituicao != null ?
                new ObjectParameter("nomeInstituicao", nomeInstituicao) :
                new ObjectParameter("nomeInstituicao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoverUtilizador", emailParameter, nomeInstituicaoParameter);
        }
    }
}
