//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscricao
    {
        public System.DateTime dataRegisto { get; set; }
        public string nomeConferencia { get; set; }
        public int anoConferencia { get; set; }
        public string emailUtilizador { get; set; }
    
        public virtual Conferencia Conferencia { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
